version: "3"
services:
  web-app:
    build:
      context: ./web_app
      dockerfile: dockerfile.web
    ports:
      - "5001:5000"
  ml-client:
    build:
      context: ./machine_learning_client
      dockerfile: dockerfile.ml
    ports:
      - "5002:5002"
    volumes:
      - ./machine_learning_client:/machine_learning_client
  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
