name: ML Client Testing
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python ${{ matrix.python-version }}
          cd machine_learning_client
          pipenv install --dev
          pipenv lock
          pipenv install -r requirements.txt

      - name: Turn on 'editable' mode
        run: |
            pipenv install -e .

      - name: Set PYTHONPATH
        run: echo "::add-path::${{ github.workspace }}/machine_learning_client"

      - name: Testing with pytest
        run: |
          cd machine_learning_client
          pipenv run python -m pytest tests